-- === USERS TABLE ===
CREATE TABLE users (
    user_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name      VARCHAR2(100) NOT NULL,
    email          VARCHAR2(150) UNIQUE NOT NULL,
    password_hash  VARCHAR2(255) NOT NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- === PASSWORD RESET TOKENS TABLE ===
CREATE TABLE password_reset_tokens (
    token_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    token        VARCHAR2(255) NOT NULL,
    expires_at   TIMESTAMP NOT NULL,
    used         NUMBER(1) DEFAULT 0,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (full_name, email, password_hash)
VALUES ('Zainab Ansari', 'zainab@example.com', 'hashed_test_password');



-- simulate reset password. 
INSERT INTO password_reset_tokens (user_id, token, expires_at)
VALUES (1, 'TEST_RESET_TOKEN_123', SYSTIMESTAMP + INTERVAL '30' MINUTE);

COMMIT;

SELECT * FROM password_reset_tokens;

SELECT * FROM users WHERE email = 'zainab@example.com';
SELECT * FROM password_reset_tokens
WHERE token = 'TEST_RESET_TOKEN_123' AND used = 0 AND expires_at > SYSTIMESTAMP;


-- === INDEXES (Optional but Recommended) ===
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_tokens_token ON password_reset_tokens(token);

-- === STORED PROCEDURES ===

-- 1️⃣ Register User
CREATE OR REPLACE PROCEDURE register_user(
    p_full_name IN VARCHAR2,
    p_email IN VARCHAR2,
    p_password_hash IN VARCHAR2
)
AS
BEGIN
    INSERT INTO users(full_name, email, password_hash)
    VALUES(p_full_name, p_email, p_password_hash);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20001, 'Email already exists.');
END;
/

-- 2️⃣ Get User by Email (for login)
CREATE OR REPLACE FUNCTION get_user_by_email(p_email IN VARCHAR2)
RETURN SYS_REFCURSOR
AS
    user_cursor SYS_REFCURSOR;
BEGIN
    OPEN user_cursor FOR
        SELECT user_id, full_name, password_hash 
        FROM users 
        WHERE email = p_email;
    RETURN user_cursor;
END;
/

-- 3️⃣ Create Reset Token
CREATE OR REPLACE PROCEDURE create_reset_token(
    p_user_id IN NUMBER,
    p_token IN VARCHAR2,
    p_expires_at IN TIMESTAMP
)
AS
BEGIN
    INSERT INTO password_reset_tokens(user_id, token, expires_at)
    VALUES(p_user_id, p_token, p_expires_at);
END;
/

-- 4️⃣ Update Password
CREATE OR REPLACE PROCEDURE update_password(
    p_user_id IN NUMBER,
    p_new_password_hash IN VARCHAR2
)
AS
BEGIN
    UPDATE users
    SET password_hash = p_new_password_hash
    WHERE user_id = p_user_id;
END;
/

-- === SAMPLE DATA (NEW) ===
INSERT INTO users (full_name, email, password_hash)
VALUES ('Ali Khan', 'ali.khan@example.com', 'hashed_password_001');

-- simulate reset password
INSERT INTO password_reset_tokens (user_id, token, expires_at)
VALUES (2, 'RESET_TOKEN_456', SYSTIMESTAMP + INTERVAL '45' MINUTE);

COMMIT;

-- === TEST QUERIES ===
-- Check user
SELECT * FROM users WHERE email = 'ali.khan@example.com';

-- Check reset token
SELECT * 
FROM password_reset_tokens
WHERE token = 'RESET_TOKEN_456'
  AND used = 0
  AND expires_at > SYSTIMESTAMP;

